#pragma once

#include "grammar-entities/Statements.hh"
#include "grammar-entities/Statement.hh"
#include "grammar-entities/Declaration.hh"
#include "grammar-entities/CallToPrint.hh"
#include "grammar-entities/Assignment.hh"
#include "grammar-entities/Conditional.hh"
#include "grammar-entities/PreLoop.hh"
#include "grammar-entities/BreakStatement.hh"
#include "grammar-entities/ContinueStatement.hh"
    
#include "grammar-entities/expressions/AddExpression.hh"
#include "grammar-entities/expressions/SubExpression.hh"
#include "grammar-entities/expressions/MultExpression.hh"
#include "grammar-entities/expressions/IntDivExpression.hh"
#include "grammar-entities/expressions/RemainderExpression.hh"
#include "grammar-entities/expressions/NumberExpression.hh"
#include "grammar-entities/expressions/IdentifierExpr.hh"
#include "grammar-entities/expressions/NestedExpression.hh"
#include "grammar-entities/expressions/EQExpression.hh"
#include "grammar-entities/expressions/NEExpression.hh"
#include "grammar-entities/expressions/LTExpression.hh"
#include "grammar-entities/expressions/GTExpression.hh"
#include "grammar-entities/expressions/GEQExpression.hh"
#include "grammar-entities/expressions/LEQExpression.hh"

#include "Program.h"